
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cricket-score-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/Sayantan2k24/flask-app-example-04.git'
    targetRevision: HEAD
    path: .
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true